### PR TITLE
Write minutes for notes/2016-06-07-IACT_DL3_Telcon.md

### PR DESCRIPTION
**Pull request by cdeil**
@jknodlseder @TarekHC @cboisson - Here's the minutes for the IACT DL3 telcon from this morning.

Please review and leave comments on whether it's OK or if you have any suggestions.

### CODE REVIEW

**Comment by TarekHC** [comment]
Minutes are perfect from my side.

Although let me add one comment, which may be a bit of an off-topic... But I think it is important. I strongly oppose the idea of using this "Scopia Visio" platform for the telcons. Linux platform is not supported, and that simply should not be allowed...

**Comment by cdeil** [comment]
@TarekHC - Thanks for having a look.

I added one point to the minutes which I forgot yesterday:

> - We agree to put back `RA_PNT` and `DEC_PNT` in the `EVENTS` header for now,
>   and add a note that DL3 producers and consumers should implement the new
>   `POINTING` table, which will likely be the long-term solution for this info.

I'm merging this now.
@cboisson @jknodlseder - Comments / corrections / additions still welcome via comments on this pull request or directly via a new pull request.

@TarekHC - Concerning your comment about the "Scopa Visio" videoconferencing system. We've discussed videoconferencing options a bit, and haven't found something better. Google hangout only works up to 10 people as far as I know an some day we might need more. Maybe eZuce in the HESS or CTA group is an option, but I've never done one where we invited non-collaboration members, not sure if that is possible or how it works. Suggestions welcome!

**Comment by jknodlseder** [comment]
One point I made yesterday both for "Data type specification" and "Units" is missing. Since I think it's an essential point I'd like that the point is added to the minutes:

By adding multiple options (e.g. not specifying 32 Bit versus 64 Bit, not specifying units) an important burden is added on the interface testing. In principle, any kind of precisions and units that are allowed need to be tested to verify that they are correctly interpreted by any software using the data format. Test data would need to be provided for all combination of options (which could become a large number of test data sets if complete flexibility on the units would be allowed).

**Comment by TarekHC** [comment]
One last comment regarding the platform used:

eZuce will require users to belong to the CTA community. But I would say all people that will usually attend these meeting does belong to CTA. So we could ask if any non-CTA member will join, in order to use an alternative platform... and use eZuce by default.

Did anyone ever use this platform?  https://discovery.renater.fr
It is open source, and the only requirement is that the host belongs to a long list of organizations. One is the Observatoire de Paris, so maybe it could be a valid option. We used this platform a couple of times in ASTERICS telcons, and it works ok.

**Comment by jknodlseder** [comment]
I was told that you have to belong to the CTA community to participate in a eZuce call, it's only a requirement for booking the meeting.

**Comment by cboisson** [comment]
Tarek, I understand the concern being on Linux and oblige to use bridge or my mobile phone (scopia works on Android) The SCOPIA/CODIAN is what is proposed by the link you mention, see here https://services.renater.fr/voix_et_image/index.
The booking is open to anybody in the federation of institution, but the tool is the one we used.

There is another possibility that works really fine, it is called Rendez-Vous. But this can only be booked for instantaneous meeting. We can test that next time, I can book and send the link a few minutes before the meeting starts. But here again nothing is perfect and you need to have Chromium/Chrome installed. Does not work for Firefox.

**Comment by TarekHC** [comment]
Yes. I understand that there is no perfect solution... I really cannot believe that in this day and age we still have this kind of trouble...

Yesterday I used the Android app for the first 15 minutes.. And it worked for ~60seconds. I assumed we were still waiting for the rest of the people, and the meeting had already started, and I heard nothing. The app also does not allow you to write in the chat, click on the copy-pasted links, etc... I thought eZuce android app was bad... But this one is even worst! :P

If there is an alternative (eZuce? Rendez-Vous?) I would push to try them. If there is none that satisfy our needs, I would then need to get a windows machine (or VM) during these meetings, which I guess would be ok for me... but will probably bring more trouble in the future (many collaborators probably also use linux).

Sorry to raise again this issue!

**Comment by cboisson** [comment]
When you open an eZuce account you are asked to finalized to choose your communities. There you need a key for CTA or HESS, MAGIC. So if you are not a member of one community already you cannot finalize the registration.

**Pull request merged**
